### ISSUE TITLE
Error when Kick/Banning a player

### ISSUE THREAD

**Issue by kyojioonaon** [JustDoom/Better-Messages#7]
Error when kicking or banning a player.
I am currently running the latest stable Velocity and have BetterMessages installed on both the proxy and paper servers.

`[21:03:05 ERROR]: Couldn't pass DisconnectEvent to bettermessages 3.3.1
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
        at com.imjustdoom.bettermessages.listener.ServerQuitListener.onPlayerChat(ServerQuitListener.java:29) ~[?:?]
        at com.imjustdoom.bettermessages.listener.Lmbda$9.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b458)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by JustDoom** [comment]
What Server Software and Minecraft version are the servers. Any plugins that manage banning/kicking specifically?

**Comment by kyojioonaon** [comment]
Apologies for the lack of explanation. The server is 1.21.1 on Paper and was tested using the minecraft:ban command.
This stack trace is from Velocity and the Paper server is not showing any errors.

**Comment by JustDoom** [comment]
Alright I will have a look after Christmas

**Comment by JustDoom** [comment]
@kyojioonaon I just realised. You are on 3.3.1 and not 3.3.2. That may have a fix for the issue
